# anytime we use docker we need sudo
sudo: required
services:
  - docker

before_install:
  - docker build -t appelsappel/docker-react -f Dockerfile.dev .

# all commands need to be executed to do all the tests
script:
  - docker run -e CI=true appelsappel/docker-react npm run test

deploy:
#  telling Travis-ci to use this to deploy
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-331856745095"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


  http://dockerreact-env.xeabtz3gmb.us-east-2.elasticbeanstalk.com/

